### ISSUE TITLE
Problem when deactivating the SwitchEventListener

### ISSUE THREAD

**Issue by StefJar** [piface/pifacedigitalio#27]
Hej

I am trying to exit my Python program when pressing a Button from the PiFace. A Event Listener is used, like described at the examples. It seems that "listener.deactivate()" makes a join on active thread. If it is the main thread of the process it fails and lead to a python hang up.
I attach a demo code:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Created on 03.04.2015

@author: stj
'''

import os
import sys
import distutils.spawn
import pifacecad
import time

def checkExecutableProgram(program):
    print('check '+program)
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK) 

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                print(' is executable')
                return exe_file

    return None

def getExecutableFileList (searchPath, extra=['py']):
    print('crawl '+searchPath)
    pL = []
    for (dirpath, dirnames, filenames) in os.walk(searchPath):
        for f in filenames:
#            if (f.endswith('py') is True) or (checkExecutableProgram(f) is not None):
#if (f.endswith('py') is True):
            if (checkExecutableProgram(f) is not None):            
                pL.append(os.path.join(dirpath,f))
    return pL


def printToLCD(line1, line2):
    global cad
    
    prtStr = line1 + '\n' + line2
    cad.lcd.clear()
    cad.lcd.write(prtStr)
    
def updateDisplayFiles():
    global gIndx
    global gFL
    global gFLlen
    
    if gIndx < 0:
        printToLCD('<none>','<none>')
        return
    l1 = '> ' + gFL[gIndx]
    l2 = '<none>' if (gIndx+1 >= gFLlen) else gFL[gIndx+1] 
    printToLCD(l1,l2)

def moveUp(e):
    global gIndx
    
    if gIndx > 0:
        gIndx -= 1
    updateDisplayFiles()

def moveDown (e):
    global gIndx
    
    if gIndx < gFLlen-1:
        gIndx += 1
    else:
        gIndx = gFLlen - 1
    updateDisplayFiles()

def execute(e):
    global gIndx
    
    if gIndx < 0:
        printToLCD('nothing to execute','')
    else:
        printToLCD('execute','wait ...')
    os.system( gFL[gIndx])
    #execfile(gFL[gIndx] , {} )
    printToLCD('finished','')

def printEvent(e):
    print(e)


def exitCB (e):
    global listener
    
    listener.deactivate()
    sys.exit(0)


if __name__ == '__main__':
    global cad
    global listener
    global actionHandler

    cad = None
    listener = None
    gFL = getExecutableFileList(os.path.expanduser("~"))
    gFLlen = len(gFL)
    gIndx = -1 if gFLlen < 1 else 0

    actionHandler ={
        6 : moveUp,
        7 : moveDown,
        5 : execute,
        4 : exitCB
        }
     
    cad = pifacecad.PiFaceCAD()
    cad.lcd.backlight_on()


    printToLCD('starter v.1.0', 'select file')
    time.sleep(2)
    updateDisplayFiles()
    try:
        listener = pifacecad.SwitchEventListener(chip=cad)
        for i in range(8):
            h = actionHandler.get(i, printEvent)
            listener.register(i, pifacecad.IODIR_FALLING_EDGE, h)
        listener.activate()
    except Exception as e:
        print(e)
        listener.deactivate()
    
    sys.exit(0)
```

and the consol error print:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pifacecommon/interrupts.py", line 339, in handle_events
    function(event)
  File "stjStarter.py", line 99, in exitCB
    listener.deactivate()
  File "/usr/lib/python3/dist-packages/pifacecommon/interrupts.py", line 220, in deactivate
    self.dispatcher.join()
  File "/usr/lib/python3.2/threading.py", line 844, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by tompreston** [comment]
So it looks like you're calling `listener.deactivate()` from within the thread which is handling the interrupt. I think the correct way to do this is to use a [barrier](https://docs.python.org/3/library/threading.html#barrier-objects) to flag when you're finished and then do the clean-up at the end of your main *thread*.

Pseudo-code:

    def cleanup():
        barrier.wait()

    def main():
        barrier = Barrier(2)
        register_interrupt_handler(4, cleanup)
        activate_interrupt_handler()
        barrier.wait()
        deactivate_interrupt_handler()
        exit()

**Comment by StefJar** [comment]
The barrier solved the problem. Maybe you can update the example section at the documentation [GitHub](http://piface.github.io/pifacecad/example.html) by adding the barrier information. Thanks for the fast reply.

**Comment by Kitzberger** [comment]
Thanks for the hint with barriers. A little snippet in the docs would have made it a lot easier for me too ;-)
