### ISSUE TITLE
ImportError: No module named 'pifacecommon'

### ISSUE THREAD

**Issue by klint-k** [piface/pifacedigitalio#34]
Just started a new install of Stretch. I could not load through apt-get tried pip3. Pip3 said it was ok. 
This is the error that I got

Traceback (most recent call last):
  File "facke_bubble1.py", line 3, in <module>
    import pifacedigitalio
  File "/usr/local/lib/python3.5/dist-packages/pifacedigitalio/__init__.py", line 18, in <module>
    from pifacecommon.interrupts import (
ImportError: No module named 'pifacecommon'

**Comment by WMRG1057** [comment]
I have been having the same problems
documentation is horrible
I have been able to get it loaded under 2.7 using pip ( will try pip3 for the 3(.5) version.)
what you are missing might be pip3 install pifacecommon

that seem to make it run under 2.7

Have not been able to find the emulator/tester or scratch files.

**Comment by WMRG1057** [comment]
After much head banging I was able to get it to load and run under both 2.7 & 3(.5), by uding the correct pip version so what you need to do is run
pip[3} install pifacedigitalio
pip[3] install pifacecommon
that seem to make it work

not sure if you need to put sudo infront but it seems to work with out it under the pi user
if you find the emulator and or the scratch mod let me know
